all : bc ws cl se mw labindex

bc : bc_0 bc_1 bc_2 bc_3 bc_4 bc_5 bc_final labindex

ws : ws_1 ws_2 ws_3 ws_4 ws_5 ws_6 ws_7 ws_8 labindex

se : se_1 se_2 se_3 se_4 se_5 se_6 se_7 labindex

cl : cl_1 cl_2 cl_3 cl_4 cl_5 cl_6 cl_7 cl_8 cl_9 cl_10

cc : cc_1

mw : mw_1

.PHONY : all

labindex : FORCE
	./buildindex.sh

gs : FORCE
	# Setup
	claat export 1KzRmack14X8G7ZFT5o_QGqr9hY894Y0MoM7wG9Gtor4
	# Code summarization and reverse engineering
	claat export 16-h1VSUMSfM8D0WWED4pPdShJrnlnPjFPfa7HzNudzo
	# Vulnerabilities and exploitation
	claat export 17KHZ8IYpzrN3nlOqKnp4DXbHd3MiKVPP2D_nxEu31jA
	# Configuration generation
	claat export 10aEBWkXHhoYe72Afggfd5eQAKPAZCb_AdjwZZ9NJ644
	# Command generation
	claat export 1HTPM1fy3lxsJ_9F-1hsKahjC0oDprQgVmsE5HZfDpis
	# Code generation
	claat export 1JwfNJvVMhNegVx-7fj71L9r5v24GA-HjbZ46cji-CfM
	# Threat intelligence and log analysis
	claat export 1abgsGqDpQnFBuOe4Gr1xIXNn-kMkIjAcX1v5oM8RvBg
	# Social engineering and phishing
	claat export 1CmMk7CorR0zrAxzfCJ2kIZSPgqBMjC3VFjSQpZMAnew
	# Securing generative applications
	claat export 1bBkgZhOgNcS1SbpxZLhFQo2SFxZcBU9D4PewHF5_6P8
	# Final project
	claat export 1cXjsJxcvZKNxb6pqVKYQpbIwwCL4HBej6-zSOJH6hxI

mw_1 : FORCE
	# BSidesPDX 2018
	# claat export 1rOYr4YyIUhvpzCPzKqKViEesNCD9yve5KuzvKJClFzc
	# M1 Setup
	claat export 1UCbgDbntH2pxlP8bxwatwg9fiIbesWomSoQAX8jRO5Q
	# M2 PMA
	claat export 1SxgVmbBX3_Fsj8_9KpVV5bU7NZmmpBFrwbY5cF3xyQQ
	# M3 AFL
	claat export 1nMJH1COPXHdLxkF1tvVHdu-9I6q7kpom9rcLm7exkkw
	# M4 angr
	claat export 1B6vgQlp6AFsW8C4TGdxVLAmmL1UrZIwHMx8vs0OFvhs
	# M5 final project RE only
	claat export 1BsU5XE73_TOg5UBvXKVHF9Hi7HyPLI7GM1q56HXxPro
	# M5b final project RE or MetaCTF
	#claat export 18ryhefKvc8cGnrGSPFbb1h5cOK_tnsOBvDvLi2HobkI
cl_1 : FORCE
	# C1.1 HW1/Setup
	claat export 1SCxbhUZNE7jlOXNkzTOaoI4GoAQxtIiBgH7PfM00Az8
	# C1.2 arp, wireshark, netsim
	claat export 1xziM5JoSWO2CG0b1X1t8_dhjYWdccZ0PDtZqsHQAaOo
	# C1.3 nmap, GCP networking
	claat export 1AdwlM9CNRhHtKBb6hjue6u-gR4hfTA3cTkanMuWwT-I
cl_2 : FORCE
	# C2.1 TCP/HTTP (netstat, lsof, nc, iperf, browser tools)
	claat export 1aGOg-1bK_fazW3Tl1tb9E8apLnya5-FfflGqVQbYyvw
	# C2.2 DNS/Recap (dig, wireshark)
	claat export 1g1eFzkRHpqlQnU_wcIV48uasKWX8DvouOOOkdTjE79o
cl_3 : FORCE
	# C3.1 python/flask guestbook
	claat export 1hSEOKiJGAd-okfgWFGupgrQb4eRt4PmjUXPFxcy1tPY
	# C3.2 SQL RDS+CloudSQL
	claat export 1MYLBTJzxaJwV_PlheOH7eifEECrHIKetDK8mGOPfLW8
	# C3.3 sqlite3 guestbook
	claat export 14Z_gNlWewTGRPsR31hiT1qF84w8TdY1tszO-i8y6hzo
	# C3.4 HW2
	claat export 1vQa9JE5S_awVIE4whRfJJOyRzc97kH2Mr7YBRwr9Hfg
cl_4 : FORCE
	# C4.1a nginx EC2 guestbook
	#claat export 1e8aHY79zf65m3v-v_syy6ZUpYsHd4bl8rFnZ9ljrJls
	# C4.1g nginx computeengine guestbook
	claat export 1lwIl9XdpezC75WnmJV5wKKIu35O4_OGe_80cfPs0564
	# C4.2g docker guestbook
	claat export 1zaZFew4_D9aRvfflHyYt2Nv6h5ADMc9wwPQ8B7ODVp4
	# C4.3 HW3
	claat export 1W06McP4v73S3vAAfSZyFFpONCY7bzo6z06qnCSyoH38
cl_5 : FORCE
	# C5.1g Storage, IAM
	claat export 1yaH-YHwD9TwNsR_8RR-dkH8_r_mEVZhjVTfoADdSbrA
	# C5.2a DynamoDB guestbook
	claat export 12TEEFFhW6ghz5pb24vqXgQumPr52vvjTGg95nZqJEno
	# C5.2g Datastore guestbook
	claat export 1N_pFWnIUN4s1gQbCqeCoKCkPkJEuI1FwlgqAB0ORe0o
cl_6 : FORCE
	# C6.1a EB guestbook
	claat export 1IERezDGuYyVIekbkglqZan_HQ93ZdnwQyC1iDr3QyuE
	# C6.1g appengine guestbook
	claat export 19l3Xgmqk9HWW5vprRCGxC3zq1Jly6x0n_TDIlL0FEMI
	# C6.2g cloud run, secret manager web proxy
	claat export 1MnWgHWHpm8gDvLthznKSQmLi90KdjZSzWu3ytho3P6M
	# C6.3a ECS guestbook
	claat export 1noYCMycw6F-sI0aRDPPl0moO743Y2-m9mKozTuMAG6w
	# C6.3g cloudrun guestbook
	claat export 1Uy-f2K5NfNE5B_f6BBcgaRfbOfb_UBQe5JtYbM7oZtc
	# C6.4g cloud function (image blurring)
	claat export 1QyFX6Xxw7U15ZzeHiMKEey_l4oUjdyvM_fhgW6aYttQ
	# C6.5g HW4
	claat export 1w5ahQ4KJegSR2Af2OGmc5gYHdNQtFIV76hSMLHmmHfE
cl_7 : FORCE
	# C7.1a Terraform guestbook AWS
	claat export 1556U_10vf3tfnbtmDp6JtZzagMjXW0uejFWP8jhfSC4
	# C7.1g Terraform guestbook GCP
	claat export 1vsVCeRkkG5WPW-Rc9V9yHtuQGbz4HQF9Dm8TXhOfpaU
	# C7.2g Kubernetes guestbook
	claat export 1Sb23-zsHTHYAsaC6T364lmL-0VzDkF6pXj6ceNfx04k
	# C7.3g APIs (slack+knowledge graph)
	claat export 1t9S3A60L3G4o0KqRllZHnHyGdLfuvtbAvQAQKrt0W_E
	# C7.4g ml apis
	claat export 1PBmtYGIRYcQShxRrtjrZ9GxlMuaFyhQ5ToZr3omuPFw
cl_8 : FORCE
	# C8.1a API Gateway lambda motd/getTime
	claat export 1FS8wBTEdp0K2Bs_A13LQiJeTLCisO6hJTCmHdOmyTmw
	# C8.2a API Gateway/Lambda guestbook
	claat export 1G67OUhA7kSMh_OjvlI4GvkjowC1zvT4sT-re_iCqi08
	# C8.2g API Gateway/Cloud functions guestbook
	claat export 1h5DdQrs6Mwxys4BuVFeonpY_AJLsQoThCjF1IaC_7Tw
	# C8.3g OAuth2 guestbook
	claat export 1A4zYpYZ31gKZPuE2krm6BGcvRuHGxU2GLZgQsM7wsGE
	# C8.4g firebase
	claat export 1nYBBYzVHmHarWTx4Yt1CHk72YfYP3sUCINEgXKoW7eY
	# cloud functions guestbook deployment manager version
	#claat export 1YPFbqOAbmft9a5QPoVk0xMu4dMbQLMJiTMKa2jMcXO0
	# lambda guestbook CDK version
	#claat export 16eHpMMWmfWVTHnqhlTpikQkUeasYEMfoy7NusoGjBTw
	# C8.5 Final project
	claat export 1KiHxAdqKO7D4Gr1Y8HmmkgTD1o0gHIR4QNNPK6djF5Y
cl_9 : FORCE
	# C9.1g bq, bl
	claat export 1jAXoFxFX5W2fhoCPMMcb1eRt95x_T_XGWueHrTGwSdY
	# C9.2g jupyter notebooks
	claat export 1R2fSw-KZ_QXzn5Q5l5jtCk-W_x_sJ0hbexhTpt-iwNw
	# C9.3g dataproc
	claat export 1unbUdzzN0CDYoK96gx2YueL6QYCjqyxDK9qRnas7-Kk
	# C9.4g dataflow
	claat export 1VrJLNSkrMjj2kRVWMf_5FV-0IoytImYzDmmofQ9GZvM
cl_10: FORCE
	# C10.1 llms
	claat export 1WewojhMgZ30yjS6vUq-Nd2NviMEvZ3aC_uSSBYtOZu4
	# C10.2 deployment manager cdn
	claat export 1eVUzpLXVADDSgQHyjPvnCsmSKGoHbWlSVMFrFdeAQx8

bc_0 : FORCE
	# 0 setup
	claat export 1NXiogMwVHp-jOIeXLu2Q7H7yC-BYXCAipOu9u5fpRCo

bc_1: FORCE
	# 0 sawtooth
	# sawtooth01 (Mine)
	claat export 1t0UIfyzonvbbKIpKa1zx1ycipfOjwoFsYn2IZdTSRKk
	# sawtooth02 (Mine)
	claat export 1CrrDaMApSTqbDaRjmFkuMr7POUzQFYpDQrkh3zdK950
	# sawtooth03 (Mine)
	claat export 1O4YyH06hjacaedy751Eav4-GGE8AMMcmLcgC9jwd6CQ
	# sawtooth04 (Mine)
	claat export 1hM0BiMmsuOXozQ6_j3Sbtvjzkdol3TkU5ThicKZZhVE

bc_2: FORCE
	# 2 solidity
	# s1_metamask_sictf
	claat export 1Sb-WScQ4IfUy1xQtEDQh38Js_1N4yI_YpAJOmmd5Ej8
	# s2_solidity_cryptozombies
	claat export 1dy4faWXdIrDK03quK6kpPxWBbmjJpUXen0fEVASPCow
	# s3_remix
	claat export 1i3YgtEoM61iixwHhse3qzk56rW8qi6_mmAPp6tY2wsE
	# s4_smartcontracts
	claat export 1vCYJSBDd8CtCtZp2PLlDYvC235chC1CSvk8_eaRRTY0

bc_3: FORCE
	# 3 sictf
	# sictf_donation_lockbox
	claat export 1TC1VRT65rSXRcTXgfca6AHtZFHI7N3ctN4gto6U9mRc
	# sictf_headsortails_lottery
	claat export 1zNRvbdPje6OGqucEUTWklhqSe39zPiGD9Nxha47L8fc
	# sictf_tokensale
	claat export 1jodKRYTCl5kdHZojNTsf3JbnL8dhVEUtMUlTyltCTuM
	# sictf_piggybank_securebank
	claat export 1PRwVOhzbl-UwxgFfL-yiRtcvHOfOfLnEUoPddxM24iY
	# sictf_recordlabel
	claat export 16NMZXmJf-nmnLeZVhhvkK_QM5x34hIVWiaDb70VyAMo
	# sictf_trustfund
	claat export 1lqJmimBtSkFToNngZEZreD3jZhABcszz-Pr_oQJm7ig
	# sictf_slotmachine_rainydayfund
	claat export 1XliBHA31PQkR-I5Z4LxI1HFI9dTTmX1uC9J4egLCsfA
	# sictf_raffle
	claat export 1NbnAWijP-xzyKcp-G6yyl1aTcMuez3NZjRqqJB_htHQ
	# sictf_scratchcard
	claat export 1M531Cub4P_8UTOyYC6Jd1aBiewePYXOlSX6WaB29I8A

bc_4: FORCE
	# 4 vyper
	# vyper_intro
	claat export 1BikDdjpVDjyRokWXNxJiTIfK9LqODhRerJWeVwYuytk
	# vyper_fundraiser
	claat export 1IISJwrxBJm8kbcPSGL03rJEUO5xGJzhxcTU-S5yfYQo
	# vyper_guestbook
	claat export 1IhbP9gwPbA3HwslIFx7nLStAwDFDfuOLdCVp8cq2pzo

bc_5: FORCE
	# 5 manticore
	# 5.1 setup
	claat export 1ZzbFk-Yo1dlwVeulNDZSzYoJJC-eWkRLj7E_Ji00_yo
	# 5.2 donation
	claat export 1L8Vihw1hGYQdA3sb1TtQGyEEj54m_JzeHth1cgO6UH4
	# 5.3 piggybank
	claat export 1iTsHx2fqnqx188Kv2ClTRJTCoxslW5eS8aez2k9RPXA
	# 5.4 lockbox
	claat export 1urL3iJieRW-mDx9kXrBD22NlQTYbtAzzFZkDeh2W6YY
	# 5.5 lottery
	claat export 1bnk73XqHxd0oc5KRjB2xc4jHVxWmozAtKlglNcR4lRA
	# 5.6 trustfund
	claat export 1UAqacMP073mR-pSfmXOJYo2ZwXAYMeOqMHSXHeIqDAo

bc_final: FORCE
	# 6 final
	claat export 1mAB9acIORNWN5XAc8pwKCFCPJNqOGV_wC00F5mkFyf4

ws_1:
	# Setup
	# 1.1 Setup
	claat export 1wa_KHELOieWE9-8ls_Vsg4Za4boH4Xydp7VOX_uWC0w
	# 1.2 Web programming
	claat export 1hg2QWIIbwvWLyMx33BKp4JpNjzJWcarXKGZW3RMbb_g
	# 1.3 Authentication
	claat export 18_EdajNo5VJZb-Veg7CzVDCCiLA4Q8amzEzRF_Wg4J4
	# 1.4 HW1 2fa-bypass-using-a-brute-force-attack
	#   (Spring 2021, Winter 2022, Winter 2023)
	#   claat export 17FL7FOT6naN1I-u4Cvo6A88sZSpsZ9P2gqS0OxojSR0
	# 1.4 HW1 2fa-broken-logic
	#   (Winter 2024)
	claat export 1uQIeFcj_Ojx91tu8o97pUhmKmdnOkbBosftNfVjaDCk
	# 1.4 HW1 Timing Side-Channel (wfp2)
	#   claat export 1CoOun-25m29tIZI-WfHWcAacg6bCGYyxpVCMZlE2BsU
	# 1.4 HW1 username-enumeration-via-response-timing
	#   claat export 102DSJHMOrP0r5mk0pWQoLaRtEnozEfPaVZBIcGkrQdI
ws_2:
	# 2.1 Access Control (file-path-traversal, access-control,
	#     information-disclosure, wfp1-fileupload)
	claat export 1fcgAGPnZ7fGWsmzkmCdx5LP16Rw7GukcNAWEfb1SdtM
	# 2.2 SSRF
	claat export 1P7Wk1OjnGx-0M-ranrdkR2mx8T2ONgr4-3z4WoN-oMY
	# 2.3 XXE
	claat export 1a35r84x6_BmQHNevwKmnUBj3CjDZCXpYufk1Udnumc8
ws_3:
	# 3.1 Command and SQL Injection
	claat export 1kZtOhMjqnfVyNJK-rhJPxbJpZlX-C7uGa1mbwvwmIks
	# Old Injection-SQLi (WFP)
	#   claat export 17mjW0pY7sKJElAkTz-zpt5WLktqm5XfAJuVqCKmU4eo
	# 3.2 HW2 WFP2 MongoDB Blind SQL Injection
	#   claat export 1WblWTNPLNRHOz5nxTKFiJ8Dpc8u0e-MEbj7_9v-3JUU
	# 3.2 HW2 conditional-responses
	#   (Winter 2024)
	claat export 1YE5pFki1XsbEktNpVbHKMN9odgJW7xcvLjX0CHwh-mA
	# 3.2 HW2 time-delays-info-retrieval
	#   (Winter 2023)
	#   claat export 1ThDR9JO4BjpVNuh1-glba6u1GTbmXy-5hERnSAHBXko
ws_4:
	# Old XSS (WFP, XSS-game)
	# claat export 1kjNMJkHUb4ZU4dbReppFVB_WY0WOHfzJjG1doxMS0gk
	# 4.1 XSS (PS)
	claat export 1AlqyaRjGCdmczJvJe1zgYdwlV7DhupDndUz4Y_P5yIE
	# 4.2 CSP/CORS (NodeJS, PS)
	claat export 1G6FDoaQkasvJavHgXG8BwQGgB5P_YwL6QX_Vu5Bi8cI
ws_5:
	# 5.1 CSRF
	claat export 1NrOCVOReEndKihcFZNyHKWgKpvIOZYefi5AaDK3SCD4
	# 5.2 Clickjacking WebCachePoisoning
	claat export 1z15wws-cTrL_H3JTZdYpACK-s4tij-pfO7tKJyH6Y3w
	# 5.3 Deserialization a8 (PHP)
	claat export 1TdiiQK4Ka6WFiQp_w89EmL3fdJFgFJfAJr3pYU3U2wI
	# 5.4 Deserialization a8 (JavaScript)
	claat export 1U0TQUivuECCd4t8NlrO6Q3ULKN8EYRdHUuuiRLW3LuI
	# 5.5 WebSocket
	claat export 1CNRZJ1RsTSaciP1k59zYHt9q8ebFDGbuDA5SObI4Th4
	# IanD/Grace Portswigger Levels
	# claat export 1E93xNRalFk7urRbzfUh19IuMY5k98MGYgdaqAVvSuRs
ws_6:
	# Tools t3 (old?)
	#claat export 1fCboO_ebRoes6-IH91FEry3EUYYZ9UFiiZTsGqN_w4M
	# 6.1 Tools setup
	claat export 1FTiXmWmlKmb1-gasIBHTi7Zk8S-cJPbKdoyj4seOhMg
	# 6.2 Discovery 1 (wfuzz, nmap, bucket-stream)
	claat export 1o6cAJ8RAa-ynLpeP6xPsZ5NSF9RYgSr-3-PSY-3gZGs
	# 6.3 Discovery 2 (wpscan)
	claat export 1xlRiQvumhVU5Qzr_zjIRXojwxH46xhYZ1lXtlTaY50w
	# 6.4 Exploitation 1 (hydra, sqlmap, xsstrike, w3af, commix)
	claat export 16XyONjg3yGjqRDxAJoYPo5I3lOgANTHvz6gzRDxcJpo
	# 6.5 Exploitation 2 (metasploit)
	claat export 1sDUBNQC5gSosULqLvv-IZrkmwfA7UUmO4Otmmi3lBwA
	# Final project
	#claat export 1GFRq2-sP7xsmoaWE8CVE0jBxiY0HRKMq86FhZTFPNao
ws_7:
	# 7.1 Cloud setup
	claat export 1QHh0wbsr51O3Qq5H4ETcrXXJA4yaiyR4XmQ3U_G0uF4
	# 7.2 Thunder CTF
	claat export 1axp_jL9bg5t5Nwsn6WVR8NOalZ1hbqMZ_OFmb1LEgXY
	# 7.3 Thunder CTF Defender
	claat export 1T6tQT3u0SLj7zKkJtpeqzDWYoUxUNKU_3xVHxMTNcEI
ws_8:
	# 8.1 AWS Flaws
	claat export 1uGiIjgIH6ZvUVmuBdlBMAHz3g6KS0PN_UpWMLtu3_78
	# 8.2 AWS Flaws2
	claat export 1joRqUHIdKA7dtjUdTUnD1fpM5inT1XzJJdMJg54rNbI
	# 8.3 AWS Serverless Goat
	claat export 1oRssROE86iWS-HjK8XnDcYt1wgW2Je8N7atoyTu8fDo
	# 8.4 AWS Cloud Goat
	#     Credentials at 1innY4rEcU0qZjWNrSdAFEjKEE-0yvsBP0lD5Inf_cGc
	claat export 1-4Lyk8f_hWbEYBqLYazIYeqVpQ-uUE698rVjJVGCc3s

se_1 : FORCE
	# S1.1 Setup, security principles 
	claat export 1vic-Z4AC2ET8Cpf26ZpeLs4Whj5_jJWfThyzHMaEpZA
se_2 : FORCE
	# S2.1 Linux file system 
	claat export 1PP_IBWEgXsrjC91YMtJWtbLVlKjx6WDs5pdHrylC260
	# S2.2 Linux security
	claat export 1l8vTb_F8Dil1uv40TPNF47qUV3Cw0SQolZO5q8Tdx3g
se_3 : FORCE
	# S3.1 Encoding and hashes
	claat export 1xKHUtBa6yNuAejyghUWYDdBJz876tyhtZkfq0DRpA58
	# S3.2 Encryption
	claat export 1V9ciRXw6Rd_-Yra3EHBX1rv7BWU9Kzt45oG6j27wJiM
	# S3.3 Digital signatures
	claat export 1b4MghQ4U29QC8xYGPmUoYVujOk4ixQIZUqQPBtqgBno
se_4 : FORCE
	# S4.1 Authentication
	claat export 17MrdjZYCm3IYxncsN-JmmwgeycKX0na8tA5buON2i04
	# S4.2 Phishing
	claat export 181BbVvvPaKaURi-b8z8FJuDr3cvgbXKo9i2EQbyE4gs
se_5 : FORCE
	# S5.1 Network forensics
	claat export 1G6oFpToktHvxr0X19s7RSo7nANSEk_ApSnIM_ph1l-A
	# S5.2 Scanning
	claat export 1-mM30nypiZ6mZ2dXCU4ZIexmoFRBvaIfbi_pJCKltGE
	# S5.3 VPNs
	claat export 1nbvexUlbjZ-NshF8lakHvL4hHgLMuvJk033ATOUoUQ4
	# S5.4 Network OSINT
	claat export 11S2d9cGNSvJ1nHi-tSrYd0CWrowhdBJ1K2GQ0NlcADY
	# S5.5 DNS, User OSINT
	claat export 1DnAp5jNDLAWrGCIgGVlgj-nbaaBlxyU5MQV70KlShWQ
se_6 : FORCE
	# S6.1 Privesc
	claat export 1-AzGILWxcR1rw2kWVppcYcWN_qoZ2xDzia0_Gy7aOBs
	# S6.2 File system backup
	claat export 11WVn_JICbG2fFZEz1yOtYd8QYiN1B5bvHe1p-tO5dEc
	# S6.3 Host forensics 
	claat export 19jSLD2_Rd3-qoRiJFA-OfdbjwdYflLttPt_jrbjdAEs
se_7 : FORCE
	# S7.1 Binary exploitation
	claat export 1Kw2VcAln-2uQ7F6SF_QjFOreO77y2FOggUSOxfb7QgU
	# S7.2 Supply-chain
	claat export 1ynNyB_62bSvn9dDfB3aKAt-oK38jDbJY2kdbZsQG_FY
	# S7.3 Tor
	claat export 1DL8_qPS5az-VmkDdZ4VMU-QQlAUmOnq575n6bjyKPS0

cc_1 : FORCE
	# CC1
	claat export 1bRq6Ggobky-JUmSV9nVpBwlXCShWkDa730D0TfDdM2Y
	# CC2
	claat export 1pIpHOjt97tH95HYLypRbw0NC5CqPMJdtAW_nmyPBDGs
	# CC3
	claat export 1mtELtuV-33rwQfk7uQ-MfzrpDjFmEmE3VSpNR6Tx5x4
	# CC4
	claat export 1kE4w4NTDhAiBfVN--w-3uG6H54wcJK1o9jrwe9qrhgI
	# CC5
	claat export 1q096CDTrHrEqQBwzJoNyu_b772J7SQgH5dKgf88msWw

update: FORCE
	claat update

FORCE:
